projects:
  tsurimeibo:
    schemaPath: amplify/backend/api/tsurimeibo/build/schema.graphql
    includes:
      - app/**/*.tsx
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: app
        region: ap-northeast-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
